---
- name: Setup a Web Server
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache Web Server
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start the Web Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create a custom homepage
      ansible.builtin.copy:
        content: "<h1>Ansible configured this website!</h1>\n"
        dest: /var/www/html/index.html
        mode: "0644"
